- name: install mysql with service
  hosts: mysql
  become: true 
  tasks:
  - name: install mysql
    ansible.builtin.package:
      name: mysql-server
      state: present
  - name: run services
    ansible.builtin.service:
      name: mysqld
      state: started
      enabled: yes
  - name: install pymsysql
    ansible.builtin.pip:
      name: PyMySQL
      state: present
      executable: pip3.9
  - name: Collect all info except settings and users by root
    community.mysql.mysql_info:
      login_user: root
      login_password: ExpenseApp@1
      login_host: mysql.devopskiran.online
  - name: create and verify password
    ansible.builtin.command: mysql_secure_installation --set-root-pass ExpenseApp@2